server:
  port: 8092
spring:
  application:
    name: provider-service
dubbo:
  application:
    name: provider-service
  registry:
    address: nacos://127.0.0.1:8848
    username: nacos
    password: nacos
  scan:
    base-packages: org.csp.learn.dubbo.nacos.provider
  protocol:
    name: dubbo
    port: 15512
